// Code generated by hertz generator.
// @author fuxingyuan
package main

import (
	controller "TikTok/biz/controller"
	mw "TikTok/biz/mw/jwt"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	//测试接口
	r.GET("/ping/", controller.Ping)
	//基础接口
	groupFirst := r.Group("/douyin") //顶头分组
	groupFirst.GET("/feed/", controller.Feed)
	groupUser := groupFirst.Group("/user")
	groupUser.POST("/register/", controller.Register)
	groupUser.POST("/login/", mw.AuthMiddleware.LoginHandler)
	groupUser.GET("/", controller.UserInfo)
	groupPublish := groupFirst.Group("/publish")
	groupPublish.POST("/action/", controller.Publish)
	groupPublish.GET("/list/", controller.PublishList)
	//互动接口
	groupFavor := groupFirst.Group("/favorite")
	groupFavor.POST("/action/", controller.FavoriteAction)
	groupFavor.GET("/list/", controller.FavoriteList)
	groupComm := groupFirst.Group("/comment")
	groupComm.POST("/action/", controller.CommentAction)
	groupComm.GET("/list/", controller.CommentList)
}
