// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameComment = "comments"

// Comment mapped from table <comments>
type Comment struct {
	CommentID  int64  `gorm:"column:comment_id;type:bigint;primaryKey;autoIncrement:true" json:"comment_id"`
	VideoID    int64  `gorm:"column:video_id;type:bigint;not null" json:"video_id"`
	UserID     int64  `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	Content    string `gorm:"column:content;type:varchar(200)" json:"content"`
	CreateDate string `gorm:"column:create_date;type:varchar(10)" json:"create_date"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
