// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFavorite = "favorites"

// Favorite mapped from table <favorites>
type Favorite struct {
	FavoriteID int64 `gorm:"column:favorite_id;type:bigint;primaryKey;autoIncrement:true" json:"favorite_id"`
	VideoID    int64 `gorm:"column:video_id;type:bigint" json:"video_id"`
	UserID     int64 `gorm:"column:user_id;type:bigint" json:"user_id"`
}

// TableName Favorite's table name
func (*Favorite) TableName() string {
	return TableNameFavorite
}
