// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserID         int64  `gorm:"column:user_id;type:bigint;primaryKey;autoIncrement:true" json:"user_id"`
	Username       string `gorm:"column:username;type:varchar(32);not null" json:"username"`
	Password       string `gorm:"column:password;type:varchar(300);not null" json:"password"`
	FollowCount    int64  `gorm:"column:follow_count;type:bigint" json:"follow_count"`
	FollowerCount  int64  `gorm:"column:follower_count;type:bigint" json:"follower_count"`
	FavoritedCount int64  `gorm:"column:favorited_count;type:bigint" json:"favorited_count"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
